CREATE DATABASE IF NOT EXISTS prisma;
USE prisma;

CREATE TABLE registerUnits(
IdU INT PRIMARY KEY AUTO_INCREMENT, 
NameInstitute VARCHAR(150) NOT NULL,
emailInstitute VARCHAR(150) NOT NULL,
city VARCHAR(100) NOT NULL,
CE /*Código escolar*/ INT(3) NOT NULL,
qtdStudents INT NOT NULL, 
pwd VARCHAR(50) NOT NULL 
);